### ISSUE TITLE
C# code snippets are not colorized

### ISSUE THREAD

**Issue by ngoquoc** [Rhetos/RhetosVSCode#1] opened 2018-09-04 10:36 UTC
## Context
There are 2 types of strings in RHE language syntax:
1. SQL scripts
2. C# code snippet

In the Rhetos.tmLanguage.json, there are some rules that define syntax highlighting rules:
1. SQL scripts are surrounded by double quotes (" and ")
2. C# code snippets are surrounded by single quotes (' and ')

## Problem
Although SQL scripts are properly highlighted in Visual Studio Code, that's unfortunately not the case for C# code snippets. 
This is because tmLanguage does not support language injection (include=source.cs) for custom captured text using RegEx:

https://macromates.com/manual/en/language_grammars#rule_keys
> captures, beginCaptures, endCaptures — these keys allow you to assign attributes to the captures of the match, begin, or end patterns. Using the captures key for a begin/end rule is short-hand for giving both beginCaptures and endCaptures with same values.

>The value of these keys is a dictionary with the key being the capture number and the value being a dictionary of attributes to assign to the captured text. Currently name is the only attribute supported. Here is an example:

>```
>{  match = '(@selector\()(.*?)(\))';
 >   captures = {
>       1 = { name = 'storage.type.objc'; };
>       3 = { name = 'storage.type.objc'; };
>    };
>};
>```
>In that example we match text like @selector(windowWillClose:) but the storage.type.objc name will only be assigned to @selector( and ).

## Solution
I have modified the tmLanguage.json to match C# code snippets using `begin` and `end` instead of `match`. The result seems better, where C# code is highlighted. However, it seems that there are some minor fixes to be provided because I noticed some incorrect highlighting in Rhe syntax, at ending brackets and semi-colons.
I'm attaching my [edited Rhetos.tmLanguage.json.zip](https://github.com/Rhetos/RhetosVSCode/files/2348250/Rhetos.tmLanguage.json.zip) so you guys can check.

**Comment by bantolov** [comment] 2018-09-04 14:52
Both versions have some issues, but your version looks better in the editor. Can you please check if the `"include": "$self"` line is necessary. If you have the time, please create the pull request.

I tried to experiment with changing the C# snippet selection pattern without much success. In both versions the C# syntax highlighting sometimes "leaks" out of the single quoted block so the rest of the DSL script does not use Rhetos highlighting. It seems that the issue is somehow triggered by the "=>" operator in the C# block.

**Comment by ngoquoc** [comment] 2018-09-04 15:23
Removing `"include": "$self"` resulted in the worst result, where C# code was partially colored, and SQL scripts were really a mess :)
I will create a PR later.

**Comment by bantolov** [comment] 2018-09-10 08:37
Closed by https://github.com/Rhetos/RhetosVSCode/pull/2

**Comment by bantolov** [comment] 2018-09-10 08:38
Closed by PR <https://github.com/Rhetos/RhetosVSCode/pull/2>

**Closed as completed** 2018-09-10 08:38 UTC
Labels: bug
